name: rotativo
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.0+11

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  
  # State management
  flutter_riverpod: ^2.4.9
  
  # Secure storage
  flutter_secure_storage: ^9.0.0
  
  # Biometric authentication
  local_auth: ^2.1.8
  
  # Forms and validation
  flutter_form_builder: ^10.0.0
  form_builder_validators: ^11.1.0
  
  # Masks
  mask_text_input_formatter: ^2.5.0
  
  # Navigation
  go_router: ^16.1.0
  
  # UI components
  fluttertoast: ^8.2.4
  url_launcher: ^6.2.2
  
  # Date formatting
  intl: ^0.19.0
  
  # Location services
  geolocator: ^10.1.0
  
  # Maps
  google_maps_flutter: ^2.5.3
  
  # UUID generator
  uuid: ^4.2.1
  
  # QR Code generation
  qr_flutter: ^4.1.0
  
  # PDF viewer
  syncfusion_flutter_pdfviewer: ^30.2.4
  
  # SVG support
  flutter_svg: ^2.0.9
  
  # Local notifications
  flutter_local_notifications: ^19.4.1
  
  # Permission handling
  permission_handler: ^11.3.0
  timezone: ^0.10.1
  
  # App info
  package_info_plus: ^8.0.2
  device_info_plus: ^11.5.0
  
  # WebView for chat
  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/config/cities/
    - assets/config/cities/Main/
    - assets/config/cities/OuroPreto/
    - assets/config/cities/Vicosa/    